<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\primerApi.Abstraccions\primerApi.Abstraccions.csproj" />
    <ProjectReference Include="..\primerApi.Entities\primerApi.Entities.csproj" />
    <ProjectReference Include="..\primerApi.Repository\primerApi.Repository.csproj" />
    <ProjectReference Include="..\primerApi.Services\primerApi.Services.csproj" />
  </ItemGroup>

</Project>
